import { defineConfig } from 'vite-plus'
import { fileURLToPath } from 'node:url'
import { defineVitestProject } from '@nuxt/test-utils/config'
import { playwright } from 'vite-plus/test/browser-playwright'

export default defineConfig({
  staged: {
    '*.{js,ts,mjs,cjs,vue}': 'vp check --no-fmt --fix',
  },
  lint: {
    plugins: [
      'oxc',
      'typescript',
      'unicorn',
      'import',
    ],
    jsPlugins: [
      '@nuxt/eslint-plugin',
      '@stylistic/eslint-plugin',
    ],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
      browser: true,
      es2024: true,
      node: true,
    },
    globals: {
      defineNuxtConfig: 'readonly',
      computed: 'readonly',
      defineEmits: 'readonly',
      defineExpose: 'readonly',
      defineProps: 'readonly',
      onMounted: 'readonly',
      onUnmounted: 'readonly',
      reactive: 'readonly',
      ref: 'readonly',
      shallowReactive: 'readonly',
      shallowRef: 'readonly',
      toRef: 'readonly',
      toRefs: 'readonly',
      watch: 'readonly',
      watchEffect: 'readonly',
      $fetch: 'readonly',
      defineAppConfig: 'readonly',
      useColorMode: 'readonly',
      useUserSession: 'readonly',
      defineOAuthDiscordEventHandler: 'readonly',
      defineOAuthBlueskyEventHandler: 'readonly',
      getAtprotoClientMetadata: 'readonly',
      hashPassword: 'readonly',
      verifyPassword: 'readonly',
      clearUserSession: 'readonly',
      getUserSession: 'readonly',
      replaceUserSession: 'readonly',
      requireUserSession: 'readonly',
      sessionHooks: 'readonly',
      setUserSession: 'readonly',
      defineOgImage: 'readonly',
      defineOgImageComponent: 'readonly',
      getNitroOrigin: 'readonly',
      updateSiteConfig: 'readonly',
      useNitroOrigin: 'readonly',
      useSiteConfig: 'readonly',
      ATPROTO_RECORD_VERSION: 'readonly',
      createAtprotoRsvp: 'readonly',
      discordEventToAtprotoRecord: 'readonly',
      getAtprotoAgent: 'readonly',
      getAtprotoClient: 'readonly',
      publishEventToAtproto: 'readonly',
      fetchEventRsvps: 'readonly',
      buildBotInviteUrl: 'readonly',
      checkBotInGuild: 'readonly',
      fetchGuildEvents: 'readonly',
      fetchGuildInfo: 'readonly',
      generateCalendar: 'readonly',
      discordRecurrenceToRRule: 'readonly',
      generateSlug: 'readonly',
      getAllGuilds: 'readonly',
      getEvent: 'readonly',
      getEventIndex: 'readonly',
      getGuild: 'readonly',
      getGuildBySlug: 'readonly',
      getGuildEvents: 'readonly',
      getGuildIndex: 'readonly',
      removeEvent: 'readonly',
      removeGuild: 'readonly',
      setEvent: 'readonly',
      setGuild: 'readonly',
      defineNuxtLink: 'readonly',
      clearNuxtData: 'readonly',
      refreshNuxtData: 'readonly',
      useAsyncData: 'readonly',
      useLazyAsyncData: 'readonly',
      useNuxtData: 'readonly',
      reloadNuxtApp: 'readonly',
      refreshCookie: 'readonly',
      useCookie: 'readonly',
      clearError: 'readonly',
      createError: 'readonly',
      isNuxtError: 'readonly',
      showError: 'readonly',
      useError: 'readonly',
      useFetch: 'readonly',
      useLazyFetch: 'readonly',
      useHead: 'readonly',
      useHeadSafe: 'readonly',
      useSeoMeta: 'readonly',
      useServerHead: 'readonly',
      useServerSeoMeta: 'readonly',
      useLoadingIndicator: 'readonly',
      callOnce: 'readonly',
      definePageMeta: 'readonly',
      prefetchComponents: 'readonly',
      preloadComponents: 'readonly',
      usePreviewMode: 'readonly',
      onNuxtReady: 'readonly',
      abortNavigation: 'readonly',
      addRouteMiddleware: 'readonly',
      defineNuxtRouteMiddleware: 'readonly',
      navigateTo: 'readonly',
      setPageLayout: 'readonly',
      useRoute: 'readonly',
      useRouter: 'readonly',
      useRuntimeHook: 'readonly',
      onPrehydrate: 'readonly',
      prerenderRoutes: 'readonly',
      setResponseStatus: 'readonly',
      useRequestEvent: 'readonly',
      useRequestFetch: 'readonly',
      useRequestHeader: 'readonly',
      useRequestHeaders: 'readonly',
      useResponseHeader: 'readonly',
      useState: 'readonly',
      useRequestURL: 'readonly',
      updateAppConfig: 'readonly',
      useAppConfig: 'readonly',
      defineNuxtPlugin: 'readonly',
      tryUseNuxtApp: 'readonly',
      useNuxtApp: 'readonly',
      useRuntimeConfig: 'readonly',
      defineEventHandler: 'readonly',
      defineLazyEventHandler: 'readonly',
      defineWebSocket: 'readonly',
      deleteCookie: 'readonly',
      getCookie: 'readonly',
      getHeader: 'readonly',
      getHeaders: 'readonly',
      getQuery: 'readonly',
      getRequestHeader: 'readonly',
      getRequestHeaders: 'readonly',
      getRequestURL: 'readonly',
      getRouterParam: 'readonly',
      getRouterParams: 'readonly',
      getValidatedQuery: 'readonly',
      getValidatedRouterParams: 'readonly',
      readBody: 'readonly',
      readFormData: 'readonly',
      readValidatedBody: 'readonly',
      sendRedirect: 'readonly',
      setCookie: 'readonly',
      setHeader: 'readonly',
      setHeaders: 'readonly',
      setResponseHeader: 'readonly',
      setResponseHeaders: 'readonly',
      useNitroApp: 'readonly',
      cachedEventHandler: 'readonly',
      cachedFunction: 'readonly',
      defineCachedEventHandler: 'readonly',
      defineCachedFunction: 'readonly',
      useEvent: 'readonly',
      defineNitroPlugin: 'readonly',
      useStorage: 'readonly',
      defineTask: 'readonly',
      runTask: 'readonly',
      Component: 'readonly',
      ComputedRef: 'readonly',
      customRef: 'readonly',
      defineAsyncComponent: 'readonly',
      defineComponent: 'readonly',
      effectScope: 'readonly',
      getCurrentInstance: 'readonly',
      h: 'readonly',
      inject: 'readonly',
      isProxy: 'readonly',
      isReactive: 'readonly',
      isReadonly: 'readonly',
      isRef: 'readonly',
      markRaw: 'readonly',
      nextTick: 'readonly',
      onActivated: 'readonly',
      onBeforeMount: 'readonly',
      onBeforeUnmount: 'readonly',
      onBeforeUpdate: 'readonly',
      onDeactivated: 'readonly',
      onErrorCaptured: 'readonly',
      onServerPrefetch: 'readonly',
      onUpdated: 'readonly',
      provide: 'readonly',
      readonly: 'readonly',
      Ref: 'readonly',
      resolveComponent: 'readonly',
      shallowReadonly: 'readonly',
      toRaw: 'readonly',
      toValue: 'readonly',
      triggerRef: 'readonly',
      unref: 'readonly',
      useAttrs: 'readonly',
      useId: 'readonly',
      useSlots: 'readonly',
      useTemplateRef: 'readonly',
      watchPostEffect: 'readonly',
      watchSyncEffect: 'readonly',
      isVue2: 'readonly',
      isVue3: 'readonly',
      onBeforeRouteLeave: 'readonly',
      onBeforeRouteUpdate: 'readonly',
      useLink: 'readonly',
    },
    ignorePatterns: [
      '**/.output',
      '**/.data',
      '**/.nuxt',
      '**/.nitro',
      '**/.cache',
      '**/dist',
      '**/node_modules',
      '**/.pnpm-store',
      '**/logs',
      '**/*.log',
      '**/.DS_Store',
      '**/.fleet',
      '**/.idea',
      '**/.env',
      '**/.env.*',
      '!**/.env.example',
      '**/test-results',
      '**/coverage/',
      '**/playwright-report/',
      '**/test-results/',
      '**/.vercel',
      '**/.netlify',
      '**/public',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-default': 'error',
      '@nuxt/prefer-import-meta': 'error',
    },
    overrides: [
      {
        files: [
          '**/*.ts',
          '**/*.tsx',
          '**/*.mts',
          '**/*.cts',
          '**/*.vue',
        ],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          'no-array-constructor': 'error',
          'no-unused-expressions': 'error',
          'no-unused-vars': [
            'error',
            {
              args: 'after-used',
              argsIgnorePattern: '^_',
              ignoreRestSiblings: true,
              vars: 'all',
              varsIgnorePattern: '^_',
            },
          ],
          'no-useless-constructor': 'error',
          'valid-typeof': 'off',
          'typescript/ban-ts-comment': [
            'error',
            {
              minimumDescriptionLength: 10,
            },
          ],
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-empty-object-type': 'error',
          'typescript/no-explicit-any': 'error',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          'typescript/no-dynamic-delete': 'error',
          'typescript/no-extraneous-class': 'error',
          'typescript/no-invalid-void-type': 'error',
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-assertion': 'off',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/unified-signatures': 'error',
          'typescript/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              prefer: 'type-imports',
            },
          ],
          'typescript/no-import-type-side-effects': 'error',
        },
      },
      {
        files: [
          '**/*.vue',
        ],
        rules: {
          'vue/no-arrow-functions-in-watch': 'error',
          'vue/no-deprecated-destroyed-lifecycle': 'error',
          'vue/no-export-in-script-setup': 'error',
          'vue/no-lifecycle-after-await': 'error',
          'vue/prefer-import-from-vue': 'error',
          'vue/valid-define-emits': 'error',
          'vue/valid-define-props': 'error',
          'vue/no-multiple-slot-args': 'warn',
          'vue/no-required-prop-with-default': 'warn',
        },
        plugins: [
          'vue',
        ],
      },
      {
        files: [
          'app/pages/**/*.{js,ts,jsx,tsx,vue}',
        ],
        rules: {
          '@nuxt/no-page-meta-runtime-values': 'error',
        },
        jsPlugins: [
          '@nuxt/eslint-plugin',
        ],
      },
      {
        files: [
          '**/.config/nuxt.?([cm])[jt]s?(x)',
          '**/nuxt.config.?([cm])[jt]s?(x)',
        ],
        rules: {
          '@nuxt/no-nuxt-config-test-key': 'error',
          '@nuxt/nuxt-config-keys-order': 'error',
        },
        jsPlugins: [
          '@nuxt/eslint-plugin',
        ],
      },
      {
        files: [
          '**/*.?([cm])[jt]s?(x)',
          '**/*.vue',
        ],
        rules: {
          '@stylistic/array-bracket-spacing': ['error', 'never'],
          '@stylistic/arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
          '@stylistic/arrow-spacing': ['error', { after: true, before: true }],
          '@stylistic/block-spacing': ['error', 'always'],
          '@stylistic/brace-style': ['error', 'stroustrup', { allowSingleLine: true }],
          '@stylistic/comma-dangle': ['error', 'always-multiline'],
          '@stylistic/comma-spacing': ['error', { after: true, before: false }],
          '@stylistic/comma-style': ['error', 'last'],
          '@stylistic/computed-property-spacing': ['error', 'never', { enforceForClassMembers: true }],
          '@stylistic/dot-location': ['error', 'property'],
          '@stylistic/eol-last': 'error',
          '@stylistic/indent': [
            'error',
            2,
            {
              ArrayExpression: 1,
              CallExpression: { arguments: 1 },
              flatTernaryExpressions: false,
              FunctionDeclaration: { body: 1, parameters: 1, returnType: 1 },
              FunctionExpression: { body: 1, parameters: 1, returnType: 1 },
              ignoreComments: false,
              ignoredNodes: ['TSUnionType', 'TSIntersectionType'],
              ImportDeclaration: 1,
              MemberExpression: 1,
              ObjectExpression: 1,
              offsetTernaryExpressions: true,
              outerIIFEBody: 1,
              SwitchCase: 1,
              tabLength: 2,
              VariableDeclarator: 1,
            },
          ],
          '@stylistic/indent-binary-ops': ['error', 2],
          '@stylistic/key-spacing': ['error', { afterColon: true, beforeColon: false }],
          '@stylistic/keyword-spacing': ['error', { after: true, before: true }],
          '@stylistic/lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
          '@stylistic/max-statements-per-line': ['error', { max: 1 }],
          '@stylistic/member-delimiter-style': [
            'error',
            {
              multiline: { delimiter: 'none', requireLast: false },
              multilineDetection: 'brackets',
              overrides: {
                interface: { multiline: { delimiter: 'none', requireLast: false } },
              },
              singleline: { delimiter: 'comma' },
            },
          ],
          '@stylistic/multiline-ternary': ['error', 'always-multiline'],
          '@stylistic/new-parens': 'error',
          '@stylistic/no-extra-parens': ['error', 'functions'],
          '@stylistic/no-floating-decimal': 'error',
          '@stylistic/no-mixed-operators': [
            'error',
            {
              allowSamePrecedence: true,
              groups: [
                ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                ['&&', '||'],
                ['in', 'instanceof'],
              ],
            },
          ],
          '@stylistic/no-mixed-spaces-and-tabs': 'error',
          '@stylistic/no-multi-spaces': 'error',
          '@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
          '@stylistic/no-tabs': 'error',
          '@stylistic/no-trailing-spaces': 'error',
          '@stylistic/no-whitespace-before-property': 'error',
          '@stylistic/object-curly-spacing': ['error', 'always'],
          '@stylistic/operator-linebreak': ['error', 'before'],
          '@stylistic/padded-blocks': ['error', { blocks: 'never', classes: 'never', switches: 'never' }],
          '@stylistic/quote-props': ['error', 'consistent-as-needed'],
          '@stylistic/quotes': ['error', 'single', { allowTemplateLiterals: 'always', avoidEscape: false }],
          '@stylistic/rest-spread-spacing': ['error', 'never'],
          '@stylistic/semi': ['error', 'never'],
          '@stylistic/semi-spacing': ['error', { after: true, before: false }],
          '@stylistic/space-before-blocks': ['error', 'always'],
          '@stylistic/space-before-function-paren': ['error', { anonymous: 'always', asyncArrow: 'always', named: 'never' }],
          '@stylistic/space-in-parens': ['error', 'never'],
          '@stylistic/space-infix-ops': 'error',
          '@stylistic/space-unary-ops': ['error', { nonwords: false, words: true }],
          '@stylistic/spaced-comment': [
            'error',
            'always',
            {
              block: { balanced: true, exceptions: ['*'], markers: ['!'] },
              line: { exceptions: ['/', '#'], markers: ['/'] },
            },
          ],
          '@stylistic/template-curly-spacing': 'error',
          '@stylistic/template-tag-spacing': ['error', 'never'],
          '@stylistic/type-annotation-spacing': ['error', {}],
          '@stylistic/type-generic-spacing': 'error',
          '@stylistic/type-named-tuple-spacing': 'error',
          '@stylistic/wrap-iife': ['error', 'any', { functionPrototypeMethods: true }],
          '@stylistic/yield-star-spacing': ['error', { after: true, before: false }],
          '@stylistic/jsx-closing-bracket-location': 'error',
          '@stylistic/jsx-closing-tag-location': 'error',
          '@stylistic/jsx-curly-brace-presence': ['error', { propElementValues: 'always' }],
          '@stylistic/jsx-curly-newline': 'error',
          '@stylistic/jsx-curly-spacing': ['error', 'never'],
          '@stylistic/jsx-equals-spacing': 'error',
          '@stylistic/jsx-first-prop-new-line': 'error',
          '@stylistic/jsx-function-call-newline': ['error', 'multiline'],
          '@stylistic/jsx-indent-props': ['error', 2],
          '@stylistic/jsx-max-props-per-line': ['error', { maximum: 1, when: 'multiline' }],
          '@stylistic/jsx-one-expression-per-line': ['error', { allow: 'single-child' }],
          '@stylistic/jsx-quotes': 'error',
          '@stylistic/jsx-tag-spacing': ['error', { afterOpening: 'never', beforeClosing: 'never', beforeSelfClosing: 'always', closingSlash: 'never' }],
          '@stylistic/jsx-wrap-multilines': [
            'error',
            {
              arrow: 'parens-new-line',
              assignment: 'parens-new-line',
              condition: 'parens-new-line',
              declaration: 'parens-new-line',
              logical: 'parens-new-line',
              prop: 'parens-new-line',
              propertyValue: 'parens-new-line',
              return: 'parens-new-line',
            },
          ],
        },
        jsPlugins: [
          '@stylistic/eslint-plugin',
        ],
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  test: {
    projects: [
      {
        test: {
          name: 'unit',
          include: ['test/unit/*.{test,spec}.ts'],
          environment: 'node',
        },
      },
      () => defineVitestProject({
        test: {
          name: 'nuxt',
          include: ['test/nuxt/*.{test,spec}.ts'],
          environment: 'nuxt',
          environmentOptions: {
            nuxt: {
              rootDir: fileURLToPath(new URL('.', import.meta.url)),
              overrides: {
                ogImage: { enabled: false },
              },
            },
          },
          browser: {
            enabled: true,
            provider: playwright(),
            instances: [
              { browser: 'chromium' },
            ],
          },
        },
      }),
    ],
    coverage: {
      enabled: true,
      provider: 'v8',
    },
  },
})
