name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 🔠 Lint project
        run: vp lint .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 📦 Install browsers
        run: vp exec playwright install

      - name: 💪 Type check
        run: vp run test:types

      - name: 🧪 Unit test
        run: vp run test:unit

      - name: 🏃 Component tests
        run: vp run test:nuxt

  browser:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 🖥️ Test project (browser)
        run: vp run test:browser
