name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 🔠 Lint project
        run: vp lint .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 📦 Install browsers
        run: vp exec playwright install

      - name: 💪 Type check
        run: vp run test:types

      - name: 🧪 Unit test
        run: vp run test:unit

      - name: 🏃 Component tests
        run: vp run test:nuxt

  browser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1

      - name: 📦 Install dependencies
        run: vp install

      - name: 🖥️ Test project (browser)
        run: vp run test:browser
